### ISSUE TITLE
Release Rust Version

### ISSUE THREAD

**Issue by kenken-xr** [linjing-lab/optimtool#2]
Rust language is very popular now and is very suitable for the development of underlying algorithms. When is a version of rust language expected.

**Comment by linjing-lab** [comment]
> Rust language is very popular now and is very suitable for the development of underlying algorithms. When is a version of rust language expected.

The cost of learning rust language is a little high. We will rewrite and reconstruct the subsequent versions on the basis of optimizing and accelerating the current version.
